import Link from "next/link";
import ConfigureAmplifyClientSide from "./components/ConfigureAmplifyClientSide";
import "@aws-amplify/ui-react/styles.css";
import "./globals.css";
import LogoutButton from "./components/LogoutButton";

import {Amplify} from "aws-amplify";
Amplify.configure({
  Auth: {
    mandatorySignId: true,
    region: "eu-west-3",
    userPoolId: "eu-west-3_2rn7vUqE6",
    userPoolWebClientId: "5q6fu1vdu9amke658k9p4ijgc7",
  },
  ssr: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="container pb-6">
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
              <br />
              <Link href="/login">Login</Link>
              <br />
              <LogoutButton />
            </li>
          </ul>
        </nav>
        <>
          <ConfigureAmplifyClientSide />
          {children}
        </>
      </body>
    </html>
  );
}
