import Link from "next/link";
import ConfigureAmplifyClientSide from "./components/ConfigureAmplifyClientSide";
import "./globals.css";
import "@aws-amplify/ui-react/styles.css";
import LogoutButton from "./components/LogoutButton";
import {Amplify} from "aws-amplify";
import {awsExports} from "../../awsExports";

Amplify.configure({
  ...awsExports,
  ssr: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="container pb-6">
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
              <br />
              <Link href="/login">Login</Link>
              <br />
              <LogoutButton />
            </li>
          </ul>
        </nav>
        <>
          <ConfigureAmplifyClientSide />
          {children}
        </>
      </body>
    </html>
  );
}
